/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EPPDialog.java
 *
 * Created on 11/09/2014, 20:17:45
 */
package zilleprojects.form;

import DAO.AbstractDAO;
import DAO.EPPDAO;
import Modelo.EPP;
import Modelo.EntidadAbstracta;
import Modelo.ParametrosSistema;
import Modelo.tablemodel.EPPTableModel;
import Modelo.tablemodel.ZilleAbstractTableModel;
import Vista.PanelAzul;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JDialog;

/**
 *
 * @author m4tuu
 */
public class EPPDialog extends ZilleDialog{

    /** Creates new form EPPDialog */
    public EPPDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ParametrosSistema.CargarParametros();
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AMEntidad = new javax.swing.JDialog();
        panelEdit = new PanelAzul();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbMedida = new javax.swing.JComboBox();
        btnCancelarEdit = new javax.swing.JButton();
        btnGuardarEdit = new javax.swing.JButton();

        AMEntidad.setLocationByPlatform(true);
        AMEntidad.setModal(true);
        AMEntidad.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        AMEntidad.setName("AMEntidad"); // NOI18N

        panelEdit.setName("panelEdit"); // NOI18N
        panelEdit.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class).getContext().getResourceMap(EPPDialog.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        panelEdit.add(jLabel1);

        txtNombre.setText(resourceMap.getString("txtNombre.text")); // NOI18N
        txtNombre.setName("txtNombre"); // NOI18N
        panelEdit.add(txtNombre);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        panelEdit.add(jLabel2);

        cmbMedida.setModel(ParametrosSistema.getComboModel(ParametrosSistema.getGrupo("EPP_MEDIDA")));
        cmbMedida.setName("cmbMedida"); // NOI18N
        panelEdit.add(cmbMedida);

        btnCancelarEdit.setText(resourceMap.getString("btnCancelarEdit.text")); // NOI18N
        btnCancelarEdit.setName("btnCancelarEdit"); // NOI18N
        btnCancelarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditActionPerformed(evt);
            }
        });
        panelEdit.add(btnCancelarEdit);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class).getContext().getActionMap(EPPDialog.class, this);
        btnGuardarEdit.setAction(actionMap.get("GuardarEntidad")); // NOI18N
        btnGuardarEdit.setText(resourceMap.getString("btnGuardarEdit.text")); // NOI18N
        btnGuardarEdit.setName("btnGuardarEdit"); // NOI18N
        panelEdit.add(btnGuardarEdit);

        javax.swing.GroupLayout AMEntidadLayout = new javax.swing.GroupLayout(AMEntidad.getContentPane());
        AMEntidad.getContentPane().setLayout(AMEntidadLayout);
        AMEntidadLayout.setHorizontalGroup(
            AMEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        AMEntidadLayout.setVerticalGroup(
            AMEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditActionPerformed
        getAMEntidad().dispose();
    }//GEN-LAST:event_btnCancelarEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AMEntidad;
    private javax.swing.JButton btnCancelarEdit;
    private javax.swing.JButton btnGuardarEdit;
    private javax.swing.JComboBox cmbMedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    protected String getTablaName() {
        return "epp";
    }

    @Override
    protected String getNombreEntidad() {
        return "Indumentaria";
    }

    @Override
    protected void limpiarEntidad() {
        epp = new EPP();
    }

    @Override
    protected AbstractDAO getDao() {
        return new EPPDAO();
    }

    @Override
    protected EntidadAbstracta getEntidadAbstracta() {
        
        return epp;
    }

    @Override
    protected void setEntidadAbstracta(EntidadAbstracta ea) {
        epp = (EPP) ea;
    }

    @Override
    protected ZilleAbstractTableModel getTableModel() {
        return tableModel;
    }

    @Override
    protected ZilleAbstractTableModel setNewTableModel() {
        tableModel = new EPPTableModel();
        return tableModel;
    }

    @Override
    protected void setTableModel(ZilleAbstractTableModel ea) {
        tableModel = (EPPTableModel) ea;
    }
    
    EPP epp = new EPP();
    EPPTableModel tableModel = new EPPTableModel();

    @Override
    protected void setTitulo() {
        this.setTitle("Elementos de protección personal");
    }

    @Override
    protected JDialog getAMEntidad() {
        return AMEntidad;
    }

    @Override
    protected JButton getBtnAceptarEntidadEdit() {
        return btnGuardarEdit;
    }

    @Override
    protected JButton getBtnCancelarEntidadEdit() {
        return btnCancelarEdit;
    }

    @Override
    protected void CargarEntidadAlEditar(EntidadAbstracta entidad) {
        epp = (EPP)entidad;
        txtNombre.setText( epp.getNombre());
        cmbMedida.setSelectedItem(epp.getMedida()== null ? "": epp.getMedida().equals("NÚMERO") ? "NÚMERO" : epp.getMedida());
    }

    @Override
    protected boolean GuardarEntidadAlEditar() {
        epp.setNombre(txtNombre.getText());
        epp.setMedida(cmbMedida.getSelectedItem().equals("NÚMERO") ? "NUMERO" : cmbMedida.getSelectedItem().toString());
        return epp.validate();
        
    }

    @Override
    protected Dimension getSizeDialogEdit() {
        return new Dimension(400, 200);
    }

    @Override
    protected Dimension getSizeMainWindow() {
        return new Dimension(900, 430);
    }
    
   
}
