/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDAutosModificar.java
 *
 * Created on 20/10/2011, 19:32:22
 */
package zilleprojects.form;

import DAO.EquiposDAO;
import Modelo.Equipos;
import Vista.OpcionPanel;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import zilleprojects.ZilleProjectsApp;

/**
 *
 * @author matuuar
 */
public class JDEquiposModificar extends javax.swing.JDialog {

    Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/zilleprojects/resources/icono.png"));

    /** Creates new form JDAutosModificar */
    public JDEquiposModificar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(botonBuscar);
        setIconImage(icono);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        filtroGrupo = new javax.swing.ButtonGroup();
        capaAzul = new Vista.PanelAzul();
        jPanel1 = new javax.swing.JPanel();
        buscarText = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDeEquipos = new javax.swing.JList();
        todosAutos = new javax.swing.JButton();
        dominioOp = new javax.swing.JRadioButton();
        nInt = new javax.swing.JRadioButton();
        marcaOp = new javax.swing.JRadioButton();
        añoOp = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nInternoText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        equipoText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        marcaText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        modeloText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        añoText = new com.toedter.calendar.JYearChooser();
        jLabel7 = new javax.swing.JLabel();
        dominioText = new javax.swing.JTextField();
        idAutolabel = new javax.swing.JLabel();
        IDequipos = new javax.swing.JLabel();
        vtoVt = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vto_seguro = new com.toedter.calendar.JDateChooser();
        eliminarEquipo = new javax.swing.JButton();
        guardarCambiosDeEquipo = new javax.swing.JButton();
        recargarInfo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        alertasText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class).getContext().getResourceMap(JDEquiposModificar.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        capaAzul.setName("capaAzul"); // NOI18N
        capaAzul.setOpaque(false);

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(375, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(375, 400));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setOpaque(false);

        buscarText.setText(resourceMap.getString("buscarText.text")); // NOI18N
        buscarText.setToolTipText(resourceMap.getString("buscarText.toolTipText")); // NOI18N
        buscarText.setName("buscarText"); // NOI18N
        buscarText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscarTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                buscarTextFocusLost(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class).getContext().getActionMap(JDEquiposModificar.class, this);
        botonBuscar.setAction(actionMap.get("buscarEquipos")); // NOI18N
        botonBuscar.setIcon(resourceMap.getIcon("botonBuscar.icon")); // NOI18N
        botonBuscar.setText(resourceMap.getString("botonBuscar.text")); // NOI18N
        botonBuscar.setToolTipText(resourceMap.getString("botonBuscar.toolTipText")); // NOI18N
        botonBuscar.setName("botonBuscar"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listaDeEquipos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaDeEquipos.setToolTipText(resourceMap.getString("listaDeEquipos.toolTipText")); // NOI18N
        listaDeEquipos.setName("listaDeEquipos"); // NOI18N
        listaDeEquipos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaDeEquiposValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaDeEquipos);

        todosAutos.setAction(actionMap.get("todosLosEquipos")); // NOI18N
        todosAutos.setText(resourceMap.getString("todosAutos.text")); // NOI18N
        todosAutos.setToolTipText(resourceMap.getString("todosAutos.toolTipText")); // NOI18N
        todosAutos.setName("todosAutos"); // NOI18N

        filtroGrupo.add(dominioOp);
        dominioOp.setSelected(true);
        dominioOp.setText(resourceMap.getString("dominioOp.text")); // NOI18N
        dominioOp.setName("dominioOp"); // NOI18N
        dominioOp.setOpaque(false);

        filtroGrupo.add(nInt);
        nInt.setText(resourceMap.getString("nInt.text")); // NOI18N
        nInt.setName("nInt"); // NOI18N
        nInt.setOpaque(false);

        filtroGrupo.add(marcaOp);
        marcaOp.setText(resourceMap.getString("marcaOp.text")); // NOI18N
        marcaOp.setName("marcaOp"); // NOI18N
        marcaOp.setOpaque(false);

        filtroGrupo.add(añoOp);
        añoOp.setText(resourceMap.getString("añoOp.text")); // NOI18N
        añoOp.setName("añoOp"); // NOI18N
        añoOp.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dominioOp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nInt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(marcaOp))
                            .addComponent(buscarText, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(todosAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(añoOp))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(todosAutos, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dominioOp)
                    .addComponent(nInt)
                    .addComponent(marcaOp)
                    .addComponent(añoOp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
        );

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        jPanel3.add(jLabel1, gridBagConstraints);

        nInternoText.setName("nInternoText"); // NOI18N
        nInternoText.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(nInternoText, gridBagConstraints);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 5);
        jPanel3.add(jLabel3, gridBagConstraints);

        equipoText.setName("equipoText"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(equipoText, gridBagConstraints);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        jPanel3.add(jLabel2, gridBagConstraints);

        marcaText.setName("marcaText"); // NOI18N
        marcaText.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(marcaText, gridBagConstraints);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        jPanel3.add(jLabel4, gridBagConstraints);

        modeloText.setName("modeloText"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(modeloText, gridBagConstraints);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        jPanel3.add(jLabel5, gridBagConstraints);

        añoText.setMinimumSize(new java.awt.Dimension(100, 25));
        añoText.setName("añoText"); // NOI18N
        añoText.setOpaque(false);
        añoText.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(añoText, gridBagConstraints);

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        jPanel3.add(jLabel7, gridBagConstraints);

        dominioText.setName("dominioText"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(dominioText, gridBagConstraints);

        idAutolabel.setText(resourceMap.getString("idAutolabel.text")); // NOI18N
        idAutolabel.setName("idAutolabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        jPanel3.add(idAutolabel, gridBagConstraints);

        IDequipos.setText(resourceMap.getString("IDequipos.text")); // NOI18N
        IDequipos.setName("IDequipos"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel3.add(IDequipos, gridBagConstraints);

        vtoVt.setMinSelectableDate(new java.util.Date(-62135755090000L));
        vtoVt.setMinimumSize(new java.awt.Dimension(100, 20));
        vtoVt.setName("vtoVt"); // NOI18N
        vtoVt.setOpaque(false);
        vtoVt.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(vtoVt, gridBagConstraints);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        jPanel3.add(jLabel6, gridBagConstraints);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 5);
        jPanel3.add(jLabel8, gridBagConstraints);

        vto_seguro.setName("vto_seguro"); // NOI18N
        vto_seguro.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(vto_seguro, gridBagConstraints);

        eliminarEquipo.setAction(actionMap.get("eliminarEquipos")); // NOI18N
        eliminarEquipo.setIcon(resourceMap.getIcon("eliminarEquipo.icon")); // NOI18N
        eliminarEquipo.setText(resourceMap.getString("eliminarEquipo.text")); // NOI18N
        eliminarEquipo.setName("eliminarEquipo"); // NOI18N

        guardarCambiosDeEquipo.setAction(actionMap.get("modificarEquipos")); // NOI18N
        guardarCambiosDeEquipo.setIcon(resourceMap.getIcon("guardarCambiosDeEquipo.icon")); // NOI18N
        guardarCambiosDeEquipo.setText(resourceMap.getString("guardarCambiosDeEquipo.text")); // NOI18N
        guardarCambiosDeEquipo.setName("guardarCambiosDeEquipo"); // NOI18N

        recargarInfo.setIcon(resourceMap.getIcon("recargarInfo.icon")); // NOI18N
        recargarInfo.setText(resourceMap.getString("recargarInfo.text")); // NOI18N
        recargarInfo.setName("recargarInfo"); // NOI18N
        recargarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargarInfoActionPerformed(evt);
            }
        });

        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setAction(actionMap.get("mostrarIngresarEquipo")); // NOI18N
        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        alertasText.setForeground(resourceMap.getColor("alertasText.foreground")); // NOI18N
        alertasText.setText(resourceMap.getString("alertasText.text")); // NOI18N
        alertasText.setName("alertasText"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(recargarInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(eliminarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(guardarCambiosDeEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, Short.MAX_VALUE))
                    .addComponent(alertasText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {eliminarEquipo, guardarCambiosDeEquipo, jButton1, jButton2, recargarInfo});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarCambiosDeEquipo)
                    .addComponent(jButton2)
                    .addComponent(eliminarEquipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recargarInfo)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertasText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {eliminarEquipo, guardarCambiosDeEquipo, jButton1, recargarInfo});

        javax.swing.GroupLayout capaAzulLayout = new javax.swing.GroupLayout(capaAzul);
        capaAzul.setLayout(capaAzulLayout);
        capaAzulLayout.setHorizontalGroup(
            capaAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capaAzulLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        capaAzulLayout.setVerticalGroup(
            capaAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capaAzulLayout.createSequentialGroup()
                .addGroup(capaAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capaAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capaAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscarTextFocusGained
        if (buscarText.getText().equals("Buscar...")) {
            buscarText.setText("");
        }
        getRootPane().setDefaultButton(botonBuscar);
    }//GEN-LAST:event_buscarTextFocusGained

    private void buscarTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscarTextFocusLost
        if (buscarText.getText().isEmpty()) {
            buscarText.setText("Buscar...");
        }
    }//GEN-LAST:event_buscarTextFocusLost

    private void listaDeEquiposValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaDeEquiposValueChanged
        if (!dlm.isEmpty()) {
            mostrarEquipo((Equipos) listaDeEquipos.getSelectedValue());
        }
        alertasText.setText(null);
    }//GEN-LAST:event_listaDeEquiposValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void recargarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargarInfoActionPerformed
       mostrarEquipo((Equipos) listaDeEquipos.getSelectedValue());
    }//GEN-LAST:event_recargarInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDEquiposModificar dialog = new JDEquiposModificar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    @Action
    public void mostrarIngresarEquipo() {
            
            JFrame mainFrame = ZilleProjectsApp.getApplication().getMainFrame();
            ingresarEquipo = new JDEquiposIngresar(mainFrame, true);
            ingresarEquipo.setLocationRelativeTo(mainFrame);
            ZilleProjectsApp.getApplication().show(ingresarEquipo);
            limpiarCampos();
            listaDeEquipos.removeAll();

    }

    public void mostrarEquipo(Equipos a) {
        try {
            IDequipos.setText(String.valueOf(a.getId()));
            nInternoText.setText(a.getN_interno());
            marcaText.setText(a.getMarca());
            equipoText.setText(a.getEquipos());
            modeloText.setText(a.getModelo());
            dominioText.setText(a.getDominio());
            añoText.setValue((int) a.getAño());
            if(a.getVto_vt()!=null){
                vtoVt.setDate(a.getVto_vt());
            }else{
                vtoVt.setDate(null);
            }
            if(a.getVto_seguro()!=null){
                vto_seguro.setDate(a.getVto_seguro());
            }else{
                vto_seguro.setDate(null);
            }
            
        } catch (NullPointerException ex) {
            System.out.println("Lista vacia de equipos.");
        }
    }
    public void limpiarCampos(){
        IDequipos.setText("0000");
            nInternoText.setText("");
            marcaText.setText("");
            equipoText.setText("");
            modeloText.setText("");
            dominioText.setText("");
            añoText.setValue(2011);
            vtoVt.setDate(null);
    }
    @Action
    public Task todosLosEquipos() {
        return new TodosLosEquiposTask(org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class));
    }

    private class TodosLosEquiposTask extends org.jdesktop.application.Task<Object, Void> {

        TodosLosEquiposTask(org.jdesktop.application.Application app) {
            
            super(app);
        }

        @Override
        protected Object doInBackground() {
            EquiposDAO adao = new EquiposDAO();
            adao.conectar();
            equipos = adao.cargarTodosMenos1();
            return null;  
        }

        @Override
        protected void succeeded(Object result) {
            dlm.removeAllElements();
            if (equipos.size() > 0) {
                for (int i = 0; i < equipos.size(); i++) {
                    dlm.add(i, equipos.get(i));
                }
            } else {
                alertasText.setText("No se encontraron coincidencias.");
                limpiarCampos();
            }
            listaDeEquipos.setModel(dlm);
        }
    }

    @Action
    public Task buscarEquipos() {
        if (buscarText.getText().isEmpty()) {
            limpiarCampos();
            return null;
        } else {
            limpiarCampos();
            if (filtroGrupo.getSelection() == dominioOp.getModel()) {
                opcion = 0;
                System.out.println("Seleccion: Dominio");
            } else if (filtroGrupo.getSelection() == nInt.getModel()) {
                opcion = 1;
                System.out.println("Seleccion: N° interno");
            } else if (filtroGrupo.getSelection() == marcaOp.getModel()) {
                opcion = 2;
                System.out.println("Seleccion: Marca");
            } else if (filtroGrupo.getSelection() == añoOp.getModel()) {
                opcion = 3;
                System.out.println("Seleccion: Año");
            }
        }
        return new BuscarEquiposTask(org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class));
    }

    private class BuscarEquiposTask extends org.jdesktop.application.Task<Object, Void> {

        BuscarEquiposTask(org.jdesktop.application.Application app) {

            super(app);
        }

        @Override
        protected Object doInBackground() {
            EquiposDAO adao = new EquiposDAO();
            adao.conectar();
            equipos = adao.buscar(opcion, buscarText.getText());
            return null;  // return your result
        }

        @Override
        protected void succeeded(Object result) {
            dlm.removeAllElements();
            if (equipos.size() > 0) {
                for (int i = 0; i < equipos.size(); i++) {
                    dlm.add(i, equipos.get(i));
                }
                alertasText.setText("");
            } else {
                 alertasText.setText("No se encontraron coincidencias.");
            }
            listaDeEquipos.setModel(dlm);
        }
    }

    @Action
    public Task eliminarEquipos() {
        if(listaDeEquipos.getSelectedValue()==null){
            alertasText.setText("No ha seleccionado algún elemento.");
            return null;
        }
        if(OpcionPanel.NO_OPTION==OpcionPanel.showConfirmDialog(null,
                "¿Realmente desea eliminar este elemento?\nYa no se podrá recuperar.", "Confirmar",
                OpcionPanel.YES_NO_OPTION)){
            return null;
        }
            
        return new EliminarEquiposTask(org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class));
    }

    private class EliminarEquiposTask extends org.jdesktop.application.Task<Object, Void> {
        Equipos eq= new Equipos();
        EliminarEquiposTask(org.jdesktop.application.Application app) {
            super(app);
            eq = (Equipos)listaDeEquipos.getSelectedValue();
        }
        @Override protected Object doInBackground() {
            EquiposDAO adao=new EquiposDAO();
            adao.conectar();
            return adao.borrar(eq);
            
        }
        @Override protected void succeeded(Object result) {
            Boolean r=(Boolean)result;
            if(r){
                limpiarCampos();
                dlm.removeElement(eq);
                alertasText.setText("Elemento eliminado."); 
                
            }else{
                OpcionPanel.showMessageDialog(null, "Ocurrió un error. Intente nuevamente", "Equipos", OpcionPanel.ERROR_MESSAGE);
            }
        }
    }

    @Action
    public Task modificarEquipos() {
        if(listaDeEquipos.getSelectedValue()==null){
            alertasText.setText("No ha seleccionado algún elementos.");
            return null;
        }
        if(OpcionPanel.NO_OPTION==OpcionPanel.showConfirmDialog(null,
                "¿Guardar cambios?", "Confirmar",
                OpcionPanel.YES_NO_OPTION)){
            return null;
        }
        return new ModificarEquiposTask(org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class));
    }

    private class ModificarEquiposTask extends org.jdesktop.application.Task<Object, Void> {
        Equipos eq= new Equipos();
        int o=0;
        ModificarEquiposTask(org.jdesktop.application.Application app) {
            super(app);
            eq = (Equipos)listaDeEquipos.getSelectedValue();
            eq.setN_interno(nInternoText.getText());
            eq.setMarca(marcaText.getText());
            eq.setModelo(modeloText.getText());
            eq.setEquipos(equipoText.getText());
            eq.setDominio(dominioText.getText());
            eq.setAño(añoText.getYear());
             if(vtoVt.getDate()!=null){
                eq.setVto_vt(vtoVt.getDate());
            }
             if(vto_seguro.getDate()!=null){
                eq.setVto_seguro(vto_seguro.getDate());
            }
                    
        }
        @Override protected Object doInBackground() {
            EquiposDAO adao=new EquiposDAO();
            adao.conectar();
            o=adao.modificar(eq);
            return null;  
        }
        @Override protected void succeeded(Object result) {
          if(o==0){
               alertasText.setText("Cambios guardados.");                             
            }else{
                OpcionPanel.showMessageDialog(null, "Ocurrió un error. Intente nuevamente", "Equipos ", OpcionPanel.ERROR_MESSAGE);
           
          }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDequipos;
    private javax.swing.JLabel alertasText;
    private javax.swing.JRadioButton añoOp;
    private com.toedter.calendar.JYearChooser añoText;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JTextField buscarText;
    private javax.swing.JPanel capaAzul;
    private javax.swing.JRadioButton dominioOp;
    private javax.swing.JTextField dominioText;
    private javax.swing.JButton eliminarEquipo;
    private javax.swing.JTextField equipoText;
    private javax.swing.ButtonGroup filtroGrupo;
    private javax.swing.JButton guardarCambiosDeEquipo;
    private javax.swing.JLabel idAutolabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaDeEquipos;
    private javax.swing.JRadioButton marcaOp;
    private javax.swing.JTextField marcaText;
    private javax.swing.JTextField modeloText;
    private javax.swing.JRadioButton nInt;
    private javax.swing.JTextField nInternoText;
    private javax.swing.JButton recargarInfo;
    private javax.swing.JButton todosAutos;
    private com.toedter.calendar.JDateChooser vtoVt;
    private com.toedter.calendar.JDateChooser vto_seguro;
    // End of variables declaration//GEN-END:variables
    ArrayList<Equipos> equipos = new ArrayList<Equipos>();
    DefaultListModel dlm = new DefaultListModel();
    int opcion = 0;
    private JDialog ingresarEquipo= new JDialog();
}
