/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDAutoIngresar.java
 *
 * Created on 19/10/2011, 20:29:41
 */
package zilleprojects.form;

import DAO.EquiposDAO;
import Modelo.Equipos;
import Vista.OpcionPanel;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author matuuar
 */
public class JDEquiposIngresar extends javax.swing.JDialog {
Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/zilleprojects/resources/icono.png"));
    /** Creates new form JDAutoIngresar */
    public JDEquiposIngresar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(icono);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new Vista.PanelAzul();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nInternoText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        equiposText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        marcaText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        modeloText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        añoText = new com.toedter.calendar.JYearChooser();
        jLabel7 = new javax.swing.JLabel();
        dominioText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        vto_vt = new com.toedter.calendar.JDateChooser();
        vto_seguro_nuevo = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        agregarAutomotor = new javax.swing.JButton();
        cancelarAutomotor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class).getContext().getResourceMap(JDEquiposIngresar.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(472, 319));

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel2.add(jLabel1, gridBagConstraints);

        nInternoText.setText(resourceMap.getString("nInternoText.text")); // NOI18N
        nInternoText.setMinimumSize(new java.awt.Dimension(100, 20));
        nInternoText.setName("nInternoText"); // NOI18N
        nInternoText.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        jPanel2.add(nInternoText, gridBagConstraints);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        jPanel2.add(jLabel3, gridBagConstraints);

        equiposText.setText(resourceMap.getString("equiposText.text")); // NOI18N
        equiposText.setMinimumSize(new java.awt.Dimension(100, 20));
        equiposText.setName("equiposText"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(equiposText, gridBagConstraints);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel2.add(jLabel2, gridBagConstraints);

        marcaText.setText(resourceMap.getString("marcaText.text")); // NOI18N
        marcaText.setMinimumSize(new java.awt.Dimension(100, 20));
        marcaText.setName("marcaText"); // NOI18N
        marcaText.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        jPanel2.add(marcaText, gridBagConstraints);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel2.add(jLabel4, gridBagConstraints);

        modeloText.setText(resourceMap.getString("modeloText.text")); // NOI18N
        modeloText.setMinimumSize(new java.awt.Dimension(100, 20));
        modeloText.setName("modeloText"); // NOI18N
        modeloText.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(modeloText, gridBagConstraints);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel2.add(jLabel5, gridBagConstraints);

        añoText.setMinimumSize(new java.awt.Dimension(100, 20));
        añoText.setName("añoText"); // NOI18N
        añoText.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(añoText, gridBagConstraints);

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        jPanel2.add(jLabel7, gridBagConstraints);

        dominioText.setMinimumSize(new java.awt.Dimension(100, 20));
        dominioText.setName("dominioText"); // NOI18N
        dominioText.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(dominioText, gridBagConstraints);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel2.add(jLabel8, gridBagConstraints);

        vto_vt.setMinimumSize(new java.awt.Dimension(100, 20));
        vto_vt.setName("vto_vt"); // NOI18N
        vto_vt.setOpaque(false);
        vto_vt.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(vto_vt, gridBagConstraints);

        vto_seguro_nuevo.setName("vto_seguro_nuevo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(vto_seguro_nuevo, gridBagConstraints);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        jPanel2.add(jLabel6, gridBagConstraints);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class).getContext().getActionMap(JDEquiposIngresar.class, this);
        agregarAutomotor.setAction(actionMap.get("agregarEquipo")); // NOI18N
        agregarAutomotor.setIcon(resourceMap.getIcon("agregarAutomotor.icon")); // NOI18N
        agregarAutomotor.setText(resourceMap.getString("agregarAutomotor.text")); // NOI18N
        agregarAutomotor.setName("agregarAutomotor"); // NOI18N

        cancelarAutomotor.setIcon(resourceMap.getIcon("cancelarAutomotor.icon")); // NOI18N
        cancelarAutomotor.setMnemonic('C');
        cancelarAutomotor.setText(resourceMap.getString("cancelarAutomotor.text")); // NOI18N
        cancelarAutomotor.setName("cancelarAutomotor"); // NOI18N
        cancelarAutomotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarAutomotorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(agregarAutomotor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelarAutomotor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {agregarAutomotor, cancelarAutomotor});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarAutomotor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarAutomotor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {agregarAutomotor, cancelarAutomotor});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarAutomotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarAutomotorActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarAutomotorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDEquiposIngresar dialog = new JDEquiposIngresar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public Task agregarEquipo() {
        if(nInternoText.getText().isEmpty()){
            OpcionPanel.showMessageDialog(null, "El campo N° INTERNO es obligatorio.", "Error!", JOptionPane.ERROR_MESSAGE);
            return null;
        }else{
            return new AgregarEquipoTask(org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class));
        }
    }

    private class AgregarEquipoTask extends org.jdesktop.application.Task<Object, Void> {
        Equipos a= new Equipos();
        int id=0;
        AgregarEquipoTask(org.jdesktop.application.Application app) {
            super(app);
            a.setN_interno(nInternoText.getText());
            a.setMarca(marcaText.getText());
            a.setEquipos(equiposText.getText());
            a.setModelo(modeloText.getText());
            a.setDominio(dominioText.getText());
            a.setAño(añoText.getYear());
            if(vto_vt.getDate()!=null){
                a.setVto_vt(vto_vt.getDate());
            }
            if(vto_seguro_nuevo.getDate()!=null){
                a.setVto_seguro(vto_seguro_nuevo.getDate());
            }
        }
        @Override protected Object doInBackground() {
            EquiposDAO aDao= new EquiposDAO();
            aDao.conectar();
            id=aDao.guardar(a);
            return null;  // return your result
        }
        @Override protected void succeeded(Object result) {
            if (id>0){
                JOptionPane.showMessageDialog(null, "Equipamiento ingresado al sistema.",
                        "Equipos", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }   else{
                JOptionPane.showMessageDialog(null, "Error! Intente nuevamente.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAutomotor;
    private com.toedter.calendar.JYearChooser añoText;
    private javax.swing.JButton cancelarAutomotor;
    private javax.swing.JTextField dominioText;
    private javax.swing.JTextField equiposText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField marcaText;
    private javax.swing.JTextField modeloText;
    private javax.swing.JTextField nInternoText;
    private com.toedter.calendar.JDateChooser vto_seguro_nuevo;
    private com.toedter.calendar.JDateChooser vto_vt;
    // End of variables declaration//GEN-END:variables
}
