/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDParteDiario.java
 *
 * Created on 03/11/2011, 00:17:40
 */
package zilleprojects.form;

import DAO.EquiposDAO;
import DAO.FuncionDAO;
import DAO.OperarioDAO;
import DAO.OrdenTrabajoDAO;
import DAO.ParteDiarioDAO;
import Modelo.Equipos;
import Modelo.EstacionServicio;
import Modelo.Funcion;
import Modelo.Materiales;
import Modelo.Obras;
import Modelo.Operario;
import Modelo.OrdenTrabajo;
import Modelo.ParteDiario;
import Modelo.Perfiles;
import Modelo.Registro;
import Modelo.RegistroEquipo;
import Modelo.TablaDatosTransporte;
import Modelo.TablaHorarioIngresoModel;
import Utils.EditorDeCeldasString;
import Vista.OpcionPanel;
import Vista.PanelAzul;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JTable;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import zilleprojects.ZilleProjectsApp;

/**
 *
 * @author matuu
 */
public class JDParteDiario extends javax.swing.JDialog {

    /** Creates new form JDParteDiario */
    Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/zilleprojects/resources/icono.png"));

    public JDParteDiario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(icono);
        setConfiguracionObra();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datosTransporteDialog = new javax.swing.JDialog();
        panelAzul2 = new PanelAzul();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaTransporte = new javax.swing.JTable();
        cerrarInfoTransporte = new javax.swing.JButton();
        aceptarInfoTransporte = new javax.swing.JButton();
        buscarEmpleado = new javax.swing.JDialog();
        jPanel8 = new PanelAzul();
        jPanel9 = new javax.swing.JPanel();
        query1 = new javax.swing.JTextField();
        botonQuery = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaEmpleados = new javax.swing.JList();
        exitDialog = new javax.swing.JButton();
        selectRow = new javax.swing.JButton();
        buscarEquipo = new javax.swing.JDialog();
        jPanel10 = new PanelAzul();
        jPanel11 = new javax.swing.JPanel();
        queryEq = new javax.swing.JTextField();
        botonQueryEq = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaEquipo = new javax.swing.JList();
        exitDialogEq = new javax.swing.JButton();
        selectEquipo = new javax.swing.JButton();
        jPanel1 = new PanelAzul();
        generalPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboOperario = new javax.swing.JComboBox();
        botonBuscarEmpleadoMostrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fechaParte = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        comboFuncion = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboObra = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        numPre = new javax.swing.JTextField();
        numPro = new javax.swing.JTextField();
        multifuncionCheck = new javax.swing.JCheckBox();
        isDesarrango = new javax.swing.JCheckBox();
        horarioPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHorario = new javax.swing.JTable();
        cerrarParteBoton = new javax.swing.JButton();
        guardarParteBoton = new javax.swing.JButton();
        equipoPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        comboEquipos = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inicialHorometroText = new javax.swing.JTextField();
        finalHorometroText = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        inicialOdometroText = new javax.swing.JTextField();
        finalOdometroText = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        estacionesCombo = new javax.swing.JComboBox();
        cantidadLitrosText = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TareaAsignadaText = new javax.swing.JTextArea();
        isTransporte = new javax.swing.JCheckBox();
        cargarDatosTransporte = new javax.swing.JButton();
        botonBuscarEquipoMostrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        observacionesText = new javax.swing.JTextArea();
        isCrearOT = new javax.swing.JCheckBox();
        outText = new javax.swing.JLabel();

        datosTransporteDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class).getContext().getResourceMap(JDParteDiario.class);
        datosTransporteDialog.setTitle(resourceMap.getString("datosTransporteDialog.title")); // NOI18N
        datosTransporteDialog.setMinimumSize(new java.awt.Dimension(625, 222));
        datosTransporteDialog.setModal(true);
        datosTransporteDialog.setName("datosTransporteDialog"); // NOI18N

        panelAzul2.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("panelAzul2.border.lineColor"), 1, true)); // NOI18N
        panelAzul2.setName("panelAzul2"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        tablaTransporte.setModel(tdt);
        tablaTransporte.setName("tablaTransporte"); // NOI18N
        jScrollPane4.setViewportView(tablaTransporte);

        cerrarInfoTransporte.setIcon(resourceMap.getIcon("cerrarInfoTransporte.icon")); // NOI18N
        cerrarInfoTransporte.setText(resourceMap.getString("cerrarInfoTransporte.text")); // NOI18N
        cerrarInfoTransporte.setName("cerrarInfoTransporte"); // NOI18N
        cerrarInfoTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarInfoTransporteActionPerformed(evt);
            }
        });

        aceptarInfoTransporte.setIcon(resourceMap.getIcon("aceptarInfoTransporte.icon")); // NOI18N
        aceptarInfoTransporte.setText(resourceMap.getString("aceptarInfoTransporte.text")); // NOI18N
        aceptarInfoTransporte.setName("aceptarInfoTransporte"); // NOI18N
        aceptarInfoTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarInfoTransporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAzul2Layout = new javax.swing.GroupLayout(panelAzul2);
        panelAzul2.setLayout(panelAzul2Layout);
        panelAzul2Layout.setHorizontalGroup(
            panelAzul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAzul2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAzul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAzul2Layout.createSequentialGroup()
                        .addComponent(aceptarInfoTransporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cerrarInfoTransporte)))
                .addContainerGap())
        );
        panelAzul2Layout.setVerticalGroup(
            panelAzul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAzul2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAzul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cerrarInfoTransporte)
                    .addComponent(aceptarInfoTransporte))
                .addContainerGap())
        );

        javax.swing.GroupLayout datosTransporteDialogLayout = new javax.swing.GroupLayout(datosTransporteDialog.getContentPane());
        datosTransporteDialog.getContentPane().setLayout(datosTransporteDialogLayout);
        datosTransporteDialogLayout.setHorizontalGroup(
            datosTransporteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAzul2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        datosTransporteDialogLayout.setVerticalGroup(
            datosTransporteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAzul2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        buscarEmpleado.setTitle(resourceMap.getString("buscarEmpleado.title")); // NOI18N
        buscarEmpleado.setLocationByPlatform(true);
        buscarEmpleado.setMinimumSize(new java.awt.Dimension(500, 300));
        buscarEmpleado.setModal(true);
        buscarEmpleado.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        buscarEmpleado.setName("buscarEmpleado"); // NOI18N
        buscarEmpleado.setResizable(false);
        buscarEmpleado.setUndecorated(true);

        jPanel8.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("jPanel8.border.lineColor"), 1, true)); // NOI18N
        jPanel8.setName("jPanel8"); // NOI18N

        jPanel9.setName("jPanel9"); // NOI18N
        jPanel9.setOpaque(false);

        query1.setText(resourceMap.getString("query1.text")); // NOI18N
        query1.setName("query1"); // NOI18N
        query1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                query1FocusGained(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class).getContext().getActionMap(JDParteDiario.class, this);
        botonQuery.setAction(actionMap.get("buscarEmpleado")); // NOI18N
        botonQuery.setIcon(resourceMap.getIcon("botonQuery.icon")); // NOI18N
        botonQuery.setText(resourceMap.getString("botonQuery.text")); // NOI18N
        botonQuery.setToolTipText(resourceMap.getString("botonQuery.toolTipText")); // NOI18N
        botonQuery.setName("botonQuery"); // NOI18N

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        listaEmpleados.setModel(listEmpl);
        listaEmpleados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaEmpleados.setName("listaEmpleados"); // NOI18N
        listaEmpleados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listaEmpleadosFocusGained(evt);
            }
        });
        jScrollPane5.setViewportView(listaEmpleados);

        exitDialog.setIcon(resourceMap.getIcon("exitDialog.icon")); // NOI18N
        exitDialog.setText(resourceMap.getString("exitDialog.text")); // NOI18N
        exitDialog.setName("exitDialog"); // NOI18N
        exitDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitDialogActionPerformed(evt);
            }
        });

        selectRow.setIcon(resourceMap.getIcon("selectRow.icon")); // NOI18N
        selectRow.setText(resourceMap.getString("selectRow.text")); // NOI18N
        selectRow.setName("selectRow"); // NOI18N
        selectRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(selectRow, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(exitDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addComponent(query1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(botonQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(query1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectRow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonQuery, query1});

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout buscarEmpleadoLayout = new javax.swing.GroupLayout(buscarEmpleado.getContentPane());
        buscarEmpleado.getContentPane().setLayout(buscarEmpleadoLayout);
        buscarEmpleadoLayout.setHorizontalGroup(
            buscarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buscarEmpleadoLayout.setVerticalGroup(
            buscarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        buscarEquipo.setTitle(resourceMap.getString("buscarEquipo.title")); // NOI18N
        buscarEquipo.setLocationByPlatform(true);
        buscarEquipo.setMinimumSize(new java.awt.Dimension(500, 300));
        buscarEquipo.setModal(true);
        buscarEquipo.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        buscarEquipo.setName("buscarEquipo"); // NOI18N
        buscarEquipo.setResizable(false);
        buscarEquipo.setUndecorated(true);

        jPanel10.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("jPanel10.border.lineColor"), 1, true)); // NOI18N
        jPanel10.setName("jPanel10"); // NOI18N

        jPanel11.setName("jPanel11"); // NOI18N
        jPanel11.setOpaque(false);

        queryEq.setName("queryEq"); // NOI18N
        queryEq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                queryEqFocusGained(evt);
            }
        });

        botonQueryEq.setAction(actionMap.get("buscarEquipos")); // NOI18N
        botonQueryEq.setIcon(resourceMap.getIcon("botonQueryEq.icon")); // NOI18N
        botonQueryEq.setToolTipText(resourceMap.getString("botonQueryEq.toolTipText")); // NOI18N
        botonQueryEq.setName("botonQueryEq"); // NOI18N

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        listaEquipo.setModel(listEq);
        listaEquipo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaEquipo.setMaximumSize(new java.awt.Dimension(100, 40));
        listaEquipo.setMinimumSize(new java.awt.Dimension(100, 40));
        listaEquipo.setName("listaEquipo"); // NOI18N
        listaEquipo.setPreferredSize(new java.awt.Dimension(300, 40));
        listaEquipo.setVisibleRowCount(16);
        listaEquipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listaEquipoFocusGained(evt);
            }
        });
        jScrollPane6.setViewportView(listaEquipo);

        exitDialogEq.setIcon(resourceMap.getIcon("exitDialogEq.icon")); // NOI18N
        exitDialogEq.setText(resourceMap.getString("exitDialogEq.text")); // NOI18N
        exitDialogEq.setName("exitDialogEq"); // NOI18N
        exitDialogEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitDialogEqActionPerformed(evt);
            }
        });

        selectEquipo.setIcon(resourceMap.getIcon("selectEquipo.icon")); // NOI18N
        selectEquipo.setText(resourceMap.getString("selectEquipo.text")); // NOI18N
        selectEquipo.setName("selectEquipo"); // NOI18N
        selectEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(queryEq, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(botonQueryEq, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(selectEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(exitDialogEq, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(queryEq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonQueryEq, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectEquipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitDialogEq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel11Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonQueryEq, queryEq});

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout buscarEquipoLayout = new javax.swing.GroupLayout(buscarEquipo.getContentPane());
        buscarEquipo.getContentPane().setLayout(buscarEquipoLayout);
        buscarEquipoLayout.setHorizontalGroup(
            buscarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buscarEquipoLayout.setVerticalGroup(
            buscarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1024, 620));
        setModal(true);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        generalPanel.setName("generalPanel"); // NOI18N
        generalPanel.setOpaque(false);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        comboOperario.setModel(operarios);
        comboOperario.setMaximumSize(new java.awt.Dimension(180, 28));
        comboOperario.setName("comboOperario"); // NOI18N
        comboOperario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboOperarioItemStateChanged(evt);
            }
        });

        botonBuscarEmpleadoMostrar.setAction(actionMap.get("mostrarBusquedaEmpleado")); // NOI18N
        botonBuscarEmpleadoMostrar.setIcon(resourceMap.getIcon("botonBuscarEmpleadoMostrar.icon")); // NOI18N
        botonBuscarEmpleadoMostrar.setText(resourceMap.getString("botonBuscarEmpleadoMostrar.text")); // NOI18N
        botonBuscarEmpleadoMostrar.setName("botonBuscarEmpleadoMostrar"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        fechaParte.setName("fechaParte"); // NOI18N
        fechaParte.setOpaque(false);
        fechaParte.setDate(new Date(System.currentTimeMillis()));

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        comboFuncion.setModel(funciones);
        comboFuncion.setName("comboFuncion"); // NOI18N
        comboFuncion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFuncionItemStateChanged(evt);
            }
        });
        comboFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFuncionActionPerformed(evt);
            }
        });

        jButton2.setAction(actionMap.get("agregarFuncion")); // NOI18N
        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        comboObra.setModel(obras
        );
        comboObra.setMaximumSize(new java.awt.Dimension(48, 28));
        comboObra.setMinimumSize(new java.awt.Dimension(48, 28));
        comboObra.setName("comboObra"); // NOI18N
        comboObra.setPreferredSize(new java.awt.Dimension(48, 28));
        comboObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboObraActionPerformed(evt);
            }
        });

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        numPre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numPre.setName("numPre"); // NOI18N

        numPro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numPro.setName("numPro"); // NOI18N

        multifuncionCheck.setText(resourceMap.getString("multifuncionCheck.text")); // NOI18N
        multifuncionCheck.setName("multifuncionCheck"); // NOI18N

        isDesarrango.setText(resourceMap.getString("isDesarrango.text")); // NOI18N
        isDesarrango.setName("isDesarrango"); // NOI18N

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addComponent(comboOperario, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscarEmpleadoMostrar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaParte, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multifuncionCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numPre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numPro, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addComponent(comboFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isDesarrango)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboObra, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(fechaParte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(numPre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numPro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multifuncionCheck)
                    .addComponent(comboOperario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarEmpleadoMostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(comboFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton2)
                    .addComponent(isDesarrango))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        generalPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonBuscarEmpleadoMostrar, comboOperario, fechaParte, jLabel1, jLabel2, jLabel5, numPre, numPro});

        generalPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboFuncion, comboObra, jButton2, jLabel3, jLabel4});

        horarioPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(-16777216,true), 1, true), resourceMap.getString("horarioPanel.border.title"))); // NOI18N
        horarioPanel.setName("horarioPanel"); // NOI18N
        horarioPanel.setOpaque(false);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablaHorario.setModel(tablaModel);
        tablaHorario.setName("tablaHorario"); // NOI18N
        tablaModel.addRegistro(new Registro());
        establecerEditorDeString(tablaHorario);
        tablaHorario.setRowHeight(25);
        tablaHorario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tablaHorarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tablaHorarioFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(tablaHorario);

        javax.swing.GroupLayout horarioPanelLayout = new javax.swing.GroupLayout(horarioPanel);
        horarioPanel.setLayout(horarioPanelLayout);
        horarioPanelLayout.setHorizontalGroup(
            horarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(horarioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
                .addContainerGap())
        );
        horarioPanelLayout.setVerticalGroup(
            horarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(horarioPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        cerrarParteBoton.setIcon(resourceMap.getIcon("cerrarParteBoton.icon")); // NOI18N
        cerrarParteBoton.setText(resourceMap.getString("cerrarParteBoton.text")); // NOI18N
        cerrarParteBoton.setName("cerrarParteBoton"); // NOI18N
        cerrarParteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarParteBotonActionPerformed(evt);
            }
        });

        guardarParteBoton.setAction(actionMap.get("guardarParteDiario")); // NOI18N
        guardarParteBoton.setIcon(resourceMap.getIcon("guardarParteBoton.icon")); // NOI18N
        guardarParteBoton.setText(resourceMap.getString("guardarParteBoton.text")); // NOI18N
        guardarParteBoton.setName("guardarParteBoton"); // NOI18N

        equipoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(-16777216,true), 1, true), resourceMap.getString("equipoPanel.border.title"), 0, 0, null, resourceMap.getColor("equipoPanel.border.titleColor"))); // NOI18N
        equipoPanel.setName("equipoPanel"); // NOI18N
        equipoPanel.setOpaque(false);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        comboEquipos.setModel(equipos);
        comboEquipos.setName("comboEquipos"); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel4.border.title"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(2, 2));

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jPanel4.add(jLabel9);

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        jPanel4.add(jLabel10);

        inicialHorometroText.setText(resourceMap.getString("inicialHorometroText.text")); // NOI18N
        inicialHorometroText.setName("inicialHorometroText"); // NOI18N
        jPanel4.add(inicialHorometroText);

        finalHorometroText.setText(resourceMap.getString("finalHorometroText.text")); // NOI18N
        finalHorometroText.setName("finalHorometroText"); // NOI18N
        jPanel4.add(finalHorometroText);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel5.border.title"))); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(2, 2));

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        jPanel5.add(jLabel11);

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        jPanel5.add(jLabel12);

        inicialOdometroText.setText(resourceMap.getString("inicialOdometroText.text")); // NOI18N
        inicialOdometroText.setName("inicialOdometroText"); // NOI18N
        jPanel5.add(inicialOdometroText);

        finalOdometroText.setText(resourceMap.getString("finalOdometroText.text")); // NOI18N
        finalOdometroText.setName("finalOdometroText"); // NOI18N
        jPanel5.add(finalOdometroText);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel6.border.title"))); // NOI18N
        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(2, 2));

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel6.add(jLabel8);

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel6.add(jLabel7);

        estacionesCombo.setModel(estaciones);
        estacionesCombo.setName("estacionesCombo"); // NOI18N
        jPanel6.add(estacionesCombo);

        cantidadLitrosText.setText(resourceMap.getString("cantidadLitrosText.text")); // NOI18N
        cantidadLitrosText.setName("cantidadLitrosText"); // NOI18N
        jPanel6.add(cantidadLitrosText);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel7.border.title"))); // NOI18N
        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        TareaAsignadaText.setColumns(15);
        TareaAsignadaText.setRows(2);
        TareaAsignadaText.setMinimumSize(new java.awt.Dimension(0, 12));
        TareaAsignadaText.setName("TareaAsignadaText"); // NOI18N
        jScrollPane3.setViewportView(TareaAsignadaText);

        jPanel7.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        isTransporte.setText(resourceMap.getString("isTransporte.text")); // NOI18N
        isTransporte.setBorder(null);
        isTransporte.setName("isTransporte"); // NOI18N

        cargarDatosTransporte.setIcon(resourceMap.getIcon("cargarDatosTransporte.icon")); // NOI18N
        cargarDatosTransporte.setText(resourceMap.getString("cargarDatosTransporte.text")); // NOI18N
        cargarDatosTransporte.setName("cargarDatosTransporte"); // NOI18N
        cargarDatosTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarDatosTransporteActionPerformed(evt);
            }
        });

        botonBuscarEquipoMostrar.setAction(actionMap.get("mostrarBusquedaEquipo")); // NOI18N
        botonBuscarEquipoMostrar.setIcon(resourceMap.getIcon("botonBuscarEquipoMostrar.icon")); // NOI18N
        botonBuscarEquipoMostrar.setText(resourceMap.getString("botonBuscarEquipoMostrar.text")); // NOI18N
        botonBuscarEquipoMostrar.setToolTipText(resourceMap.getString("botonBuscarEquipoMostrar.toolTipText")); // NOI18N
        botonBuscarEquipoMostrar.setName("botonBuscarEquipoMostrar"); // NOI18N

        javax.swing.GroupLayout equipoPanelLayout = new javax.swing.GroupLayout(equipoPanel);
        equipoPanel.setLayout(equipoPanelLayout);
        equipoPanelLayout.setHorizontalGroup(
            equipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(equipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(equipoPanelLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                    .addGroup(equipoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboEquipos, 0, 589, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscarEquipoMostrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(equipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(equipoPanelLayout.createSequentialGroup()
                        .addComponent(isTransporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargarDatosTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        equipoPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel4, jPanel5});

        equipoPanelLayout.setVerticalGroup(
            equipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(equipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(equipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(comboEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(isTransporte)
                        .addComponent(cargarDatosTransporte))
                    .addComponent(botonBuscarEquipoMostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(equipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        equipoPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cargarDatosTransporte, comboEquipos});

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(-16777216,true), 1, true), resourceMap.getString("jPanel3.border.title"), 0, 0, null, resourceMap.getColor("jPanel3.border.titleColor"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setOpaque(false);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        observacionesText.setColumns(20);
        observacionesText.setRows(3);
        observacionesText.setName("observacionesText"); // NOI18N
        jScrollPane2.setViewportView(observacionesText);

        isCrearOT.setText(resourceMap.getString("isCrearOT.text")); // NOI18N
        isCrearOT.setName("isCrearOT"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isCrearOT)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isCrearOT)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        outText.setForeground(resourceMap.getColor("outText.foreground")); // NOI18N
        outText.setText(resourceMap.getString("outText.text")); // NOI18N
        outText.setName("outText"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(outText, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarParteBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cerrarParteBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(horarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(equipoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(generalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equipoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(guardarParteBoton)
                    .addComponent(cerrarParteBoton)
                    .addComponent(outText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cerrarParteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarParteBotonActionPerformed
    tablaModel = new TablaHorarioIngresoModel();
    this.dispose();

}//GEN-LAST:event_cerrarParteBotonActionPerformed

private void comboOperarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboOperarioItemStateChanged
    outText.setText("");
    int func = ((Operario) comboOperario.getSelectedItem()).getFuncion();
    comboFuncion.setSelectedItem(new Funcion(func));
}//GEN-LAST:event_comboOperarioItemStateChanged

private void cargarDatosTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarDatosTransporteActionPerformed
    if (tdt.getRowCount() != 4) {
        tdt.addRegistro(new Materiales("CALCAREO"));
        tdt.addRegistro(new Materiales("ARENA"));
        tdt.addRegistro(new Materiales("AGUA"));
        tdt.addRegistro(new Materiales("OTROS"));
    }
    tablaTransporte.setModel(tdt);
    datosTransporteDialog.setSize(625, 222);
    datosTransporteDialog.setLocationRelativeTo(this);
    datosTransporteDialog.setVisible(true);

    tablaTransporte.getColumnModel().getColumn(0).setMaxWidth(40);
    tablaTransporte.getColumnModel().getColumn(5).setMinWidth(150);

}//GEN-LAST:event_cargarDatosTransporteActionPerformed

private void cerrarInfoTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarInfoTransporteActionPerformed
    
    datosTransporteDialog.dispose();

}//GEN-LAST:event_cerrarInfoTransporteActionPerformed

private void aceptarInfoTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarInfoTransporteActionPerformed


    for (int i = 0; i < tdt.getRowCount(); i++) {
        Materiales m = tdt.getFila(i);
        if (m.isOk()) {
            isTransporte.setSelected(true);
            regDatosTransp.add(m);
        }
    }

    
    datosTransporteDialog.dispose();
}//GEN-LAST:event_aceptarInfoTransporteActionPerformed

private void tablaHorarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablaHorarioFocusGained
    if (esp) {
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(fechaParte.getDate());
        if (gc.get(Calendar.DAY_OF_WEEK) == Calendar.SATURDAY) {
            Registro r = tablaModel.getFila(0);
            r.setEspecial(true);
            tablaModel.insertarFila(r, 0);

        } else if (gc.get(Calendar.DAY_OF_WEEK) == Calendar.SUNDAY) {
            Registro r = tablaModel.getFila(0);
            r.setEspecial(true);
            tablaModel.insertarFila(r, 0);
        } else {
            Registro r = tablaModel.getFila(0);
            r.setEspecial(false);
            tablaModel.insertarFila(r, 0);
        }
        esp = false;
    }
    //System.out.print("Me fije en la fecha :p\n");
}//GEN-LAST:event_tablaHorarioFocusGained

private void tablaHorarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablaHorarioFocusLost
    esp = true;
}//GEN-LAST:event_tablaHorarioFocusLost

private void comboFuncionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFuncionItemStateChanged

}//GEN-LAST:event_comboFuncionItemStateChanged

private void comboFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFuncionActionPerformed
    outText.setText("");
    int func = ((Operario) comboOperario.getSelectedItem()).getFuncion();
    if (func != ((Funcion) comboFuncion.getSelectedItem()).getId() && !multifuncionCheck.isSelected()) {
        multifuncionCheck(1);
    }
    if (func == ((Funcion) comboFuncion.getSelectedItem()).getId() && multifuncionCheck.isSelected()) {
        multifuncionCheck(2);
    }
}//GEN-LAST:event_comboFuncionActionPerformed

private void query1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_query1FocusGained
    buscarEmpleado.getRootPane().setDefaultButton(botonQuery);

}//GEN-LAST:event_query1FocusGained

private void exitDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitDialogActionPerformed
    buscarEmpleado.dispose();
    query1.setText("");
    listEmpl.removeAllElements();
}//GEN-LAST:event_exitDialogActionPerformed

private void selectRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectRowActionPerformed
    if (listEmpl.isEmpty() || listaEmpleados.isSelectionEmpty()) {
        //nothing
    } else {
        comboOperario.setSelectedItem((Operario) listaEmpleados.getSelectedValue());
        buscarEmpleado.dispose();
        query1.setText("");
        listEmpl.removeAllElements();
    }
}//GEN-LAST:event_selectRowActionPerformed

private void listaEmpleadosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaEmpleadosFocusGained
    buscarEmpleado.getRootPane().setDefaultButton(selectRow);
}//GEN-LAST:event_listaEmpleadosFocusGained

private void queryEqFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_queryEqFocusGained
    buscarEquipo.getRootPane().setDefaultButton(botonQueryEq);
}//GEN-LAST:event_queryEqFocusGained

private void listaEquipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaEquipoFocusGained
    buscarEquipo.getRootPane().setDefaultButton(selectEquipo);
}//GEN-LAST:event_listaEquipoFocusGained

private void exitDialogEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitDialogEqActionPerformed
    buscarEquipo.dispose();
    queryEq.setText("");
    listEq.removeAllElements();
}//GEN-LAST:event_exitDialogEqActionPerformed

private void selectEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectEquipoActionPerformed
    if (listEq.isEmpty() || listaEquipo.isSelectionEmpty()) {
        //nothing
    } else {
        comboEquipos.setSelectedItem((Equipos) listaEquipo.getSelectedValue());
        buscarEquipo.dispose();
        queryEq.setText("");
        listEq.removeAllElements();
    }
}//GEN-LAST:event_selectEquipoActionPerformed

    private void comboObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboObraActionPerformed
        setConfiguracionObra();
    }//GEN-LAST:event_comboObraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDParteDiario dialog = new JDParteDiario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void establecerEditorDeString(JTable t) {
        final EditorDeCeldasString string = new EditorDeCeldasString(10);
        string.setHorizontalAlignment(EditorDeCeldasString.LEFT);
        DefaultCellEditor editorEnteros = new DefaultCellEditor(string) {

            @Override
            public Object getCellEditorValue() {
                return string.getValue();
            }
        };

        t.setDefaultEditor(String.class, editorEnteros);
    }

    private void setConfiguracionObra(){
        obra = ((Obras)comboObra.getSelectedItem());
        for (Component c: horarioPanel.getComponents()){
            c.setEnabled(obra.isTieneRegistro());
        }
        tablaHorario.setEnabled(obra.isTieneRegistro());
        comboFuncion.setEnabled(obra.isTieneRegistro());
        isDesarrango.setEnabled(obra.isTieneRegistro());
        multifuncionCheck.setEnabled(obra.isTieneRegistro());
        for (Component c: equipoPanel.getComponents()){
            if(c instanceof javax.swing.JPanel){
                for(Component cc: ((javax.swing.JPanel) c).getComponents()){
                    cc.setEnabled(obra.isTieneEquipo());
                }
            }else{
                c.setEnabled(obra.isTieneEquipo());
            }
        }
        TareaAsignadaText.setEnabled(obra.isTieneEquipo());
        isCrearOT.setEnabled(obra.isTieneEquipo());
    }
    
    private void multifuncionCheck(final int i) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                switch (i) {
                    case 1:
                        OpcionPanel.showMessageDialog(null, "Se activo la MULTIFUNCION para este parte diario.", "Multifunción", OpcionPanel.INFORMATION_MESSAGE);
                        multifuncionCheck.setSelected(true);
                        break;
                    case 2:
                        if (OpcionPanel.YES_OPTION
                                == OpcionPanel.showConfirmDialog(null, "Ha vuelto a seleccionar la función del empleado:\n"
                                + "¿Desactivar el tilde de multifunción?", "Multifunción", OpcionPanel.YES_NO_OPTION)) {
                            multifuncionCheck.setSelected(false);
                        }
                        break;
                }

            }
        });

    }

    @Action
    public Task agregarFuncion() {
        newFc = OpcionPanel.showInputDialog(this, "Función: ");
        if (newFc == null || newFc.isEmpty()) {
            return null;
        }
        return new AgregarFuncionTask(org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class));
    }

    
    private class AgregarFuncionTask extends org.jdesktop.application.Task<Object, Void> {

        Funcion fun = new Funcion(newFc);
        int r = -1;

        AgregarFuncionTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to AgregarFuncionTask fields, here.
            super(app);
        }

        @Override
        protected Object doInBackground() {
            // Your Task's code here.  This method runs
            // on a background thread, so don't reference
            // the Swing GUI from here.
            FuncionDAO fdao = new FuncionDAO();
            fdao.conectar();
            r = fdao.guardar(fun);
            return null;  // return your result
        }

        @Override
        protected void succeeded(Object result) {
            if (r >= 0) {
                fun.setId(r);
                funciones.addElement(fun);
            } else {
                OpcionPanel.showMessageDialog(null, "Compruebe que ya no exista una \nfunción con ese nombre.", "Error", OpcionPanel.ERROR_MESSAGE);
            }
        }
    }

    public boolean horarioCompleto() {
        Registro aux = tablaModel.getFila(0);
        try {
            if (aux.getHs_salida().toString().isEmpty() || aux.getHs_llegada().toString().isEmpty()
                    || aux.getHs_inicio().toString().isEmpty() || aux.getHs_fin().toString().isEmpty()
                    || aux.getHs_ialmuerzo().toString().isEmpty() || aux.getHs_falmuerzo().toString().isEmpty()) {
                return false;
            }
        } catch (NullPointerException ex) {
            return false;
        }
        return true;
    }

    @Action
    public Task guardarParteDiario() {
        if (OpcionPanel.YES_OPTION == OpcionPanel.showConfirmDialog(this, "¿Desea guardar?", "Guardando...", OpcionPanel.YES_NO_OPTION)) {
            if (fechaParte.getDate() == null || numPre.getText().isEmpty() || numPro.getText().isEmpty()){
                OpcionPanel.showMessageDialog(this, "Falta completar algunos campos", "Datos imcompletos", OpcionPanel.ERROR_MESSAGE);
                return null;
                
            }
            if(obra.isTieneRegistro() && !horarioCompleto()){
                OpcionPanel.showMessageDialog(this, "Complete los horarios, son requeridos para la obra seleccionada", "Datos imcompletos", OpcionPanel.ERROR_MESSAGE);
                return null;  
            }
        } else {
            return null;
        }
        return new GuardarParteDiarioTask(org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class));
    }

    private class GuardarParteDiarioTask extends org.jdesktop.application.Task<Object, Void> {

        ParteDiario pd = new ParteDiario();
        Registro reg = new Registro();
        Materiales mat = new Materiales();
        RegistroEquipo regEq = new RegistroEquipo();
        public ArrayList<Materiales> datosTr = new ArrayList<Materiales>();
        OrdenTrabajo ot = new OrdenTrabajo();
        int rPD = -1;
        int rOT = -1;
        boolean creandoOT = false;

        GuardarParteDiarioTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to GuardarParteDiarioTask fields, here.
            super(app);
            //pasamos la obra seleccionada al perfil
            perfil.setObra(obra);
            pd.setFecha(fechaParte.getDate());
            pd.setIdOperario(((Operario) comboOperario.getSelectedItem()).getId());
            pd.setIdObra(obra.getId());
            pd.setNumero(numPre.getText(), numPro.getText());
            pd.setObservaciones(observacionesText.getText());
            pd.setIdSituacion(1);
            // Depende del perfil
            if(obra.isTieneRegistro()){
                pd.setIdFuncion(((Funcion) comboFuncion.getSelectedItem()).getId());
                pd.setMultifuncion(multifuncionCheck.isSelected());
                pd.setDesarraigo(isDesarrango.isSelected());
                reg = tablaModel.getFila(0);
                GregorianCalendar gc = new GregorianCalendar();
                gc.setTime(fechaParte.getDate());
                reg.setFecha(reg.getStringWFecha(gc));
            }
            if(obra.isTieneEquipo()){
                regEq.setIdEquipo(((Equipos) comboEquipos.getSelectedItem()).getId());
                regEq.setDatosCarga(isTransporte.isSelected());
                regEq.setIniHoro(inicialHorometroText.getText());
                regEq.setFinHoro(finalHorometroText.getText());
                regEq.setIniOdo(inicialOdometroText.getText());
                regEq.setFinOdo(finalOdometroText.getText());
                regEq.setCantCombustible(cantidadLitrosText.getText());
                regEq.setEstacionServicioID(((EstacionServicio)estacionesCombo.getSelectedItem()).getEstacionServicioID());
                regEq.setTarea(TareaAsignadaText.getText());
                if (regEq.isDatosCarga()) {
                    datosTr = regDatosTransp;
                }
            
                creandoOT = isCrearOT.isSelected();
                if(creandoOT){

                    ot.setDetalleServicio(pd.getObservaciones());
                    ot.setFecha(pd.getFecha());
                    ot.setFechaApertura(pd.getFecha());
                    ot.setHs(regEq.getFinHoro());
                    ot.setKm(regEq.getFinOdo());
                    ot.setSolicitante(((Operario) comboOperario.getSelectedItem()).getNombre());

                    ot.setnInternoID(regEq.getIdEquipo());
                    ot.setnInterno(((Equipos) comboEquipos.getSelectedItem()).getN_interno());
                    ot.setMantenimiento("CORRECTIVO");

                }
            }
            

        }

        @Override
        protected Object doInBackground() {
            ParteDiarioDAO pdao = new ParteDiarioDAO();
            pdao.conectar();
            if(pdao.numeroExistsNew(pd.getNumero())){
                rPD=-10;
                return null;
            }
            //evaluo el desarraigo del parte diario y el desarraigo del operario
            reg.calcular(perfil, (pd.isDesarraigo()| ((Operario) comboOperario.getSelectedItem()).isDesarraigo()));
            
            rPD = pdao.guardar(perfil, pd, reg, regEq, datosTr);
            //creo la OT si se chequeo el checkbox
            if(creandoOT){
                OrdenTrabajoDAO otDao = new OrdenTrabajoDAO();
                otDao.conectar();
                rOT = otDao.guardar(ot);
            }
            return null;  // return your result
        }

        @Override
        protected void succeeded(Object result) {
            if(rPD == -10){
                OpcionPanel.showMessageDialog(null, "¡No se pudo guardar!\n"
                        + "Existe un parte diario\n"
                        + "almacenado con ese número de talón.", "Error", OpcionPanel.ERROR_MESSAGE);
            }else {
            if (rPD < 0) {
                OpcionPanel.showMessageDialog(null, "¡No se pudo guardar!\n"
                        + "Intente nuevamente.", "Error", OpcionPanel.ERROR_MESSAGE);
            } else {
                resetearForm();
                outText.setText("Datos guardados.");

            }
            }
            if(creandoOT){
                if(rOT==-1){
                    OpcionPanel.showMessageDialog(null, "¡No se pudo crear la Orden de trabajo!\n"
                        + "Intente nuevamente.", "Error", OpcionPanel.ERROR_MESSAGE);
                }else{
                    JFrame mainFrame = ZilleProjectsApp.getApplication().getMainFrame();
                    JDOrdenTrabajo ordenDeTrabajo = new JDOrdenTrabajo(mainFrame, true);
                    ordenDeTrabajo.setLocationRelativeTo(mainFrame); 
                    ordenDeTrabajo.setSelectedOT(ot);
                    ZilleProjectsApp.getApplication().show(ordenDeTrabajo);
                    
                }
            }
        }
    }

    public void resetearForm() {
        multifuncionCheck.setSelected(false);
        fechaParte.setDate(new Date());
        //comboFuncion.setSelectedIndex(0);
        comboObra.setSelectedIndex(0);
        setConfiguracionObra();
        comboOperario.setSelectedIndex(0);
        numPre.setText("");
        numPro.setText("");
        inicialHorometroText.setText("");
        inicialOdometroText.setText("");
        finalHorometroText.setText("");
        finalOdometroText.setText("");
        comboEquipos.setSelectedIndex(0);
        cantidadLitrosText.setText("");
        estacionesCombo.setSelectedIndex(0);
        TareaAsignadaText.setText("");
        isTransporte.setSelected(false);
        observacionesText.setText("");
        tablaModel.insertarFila(new Registro(), 0);
        regDatosTransp.clear();
        tdt = new TablaDatosTransporte();
        isCrearOT.setSelected(false);
    }

    @Action
    public Task buscarEmpleado() {
        if (query1.getText().isEmpty()) {
            return null;
        }
        return new BuscarEmpleadoTask(org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class));
    }

    private class BuscarEmpleadoTask extends org.jdesktop.application.Task<Object, Void> {

        ArrayList<Operario> opList = new ArrayList<Operario>();
        String query = query1.getText();

        BuscarEmpleadoTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to BuscarEmpleadoTask fields, here.
            super(app);
        }

        @Override
        protected Object doInBackground() {
            // Your Task's code here.  This method runs
            // on a background thread, so don't reference
            // the Swing GUI from here.
            OperarioDAO odao = new OperarioDAO();
            odao.conectar();
            opList = odao.buscar(query);
            return null;  // return your result
        }

        @Override
        protected void succeeded(Object result) {
            listEmpl.removeAllElements();
            if (opList.isEmpty()) {
                listEmpl.addElement("Sin resultados");
                listaEmpleados.setEnabled(false);
            } else {
                for (int i = 0; i < opList.size(); i++) {
                    listEmpl.addElement((Operario) opList.get(i));
                }
                listaEmpleados.setEnabled(true);
            }
        }
    }

    @Action
    public void mostrarBusquedaEmpleado() {

        buscarEmpleado.setLocationRelativeTo(horarioPanel);
        buscarEmpleado.setVisible(true);
    }

    @Action
    public void mostrarBusquedaEquipo() {

        buscarEquipo.setLocationRelativeTo(botonBuscarEquipoMostrar);
        buscarEquipo.setVisible(true);
    }

    @Action
    public Task buscarEquipos() {
        if (queryEq.getText().isEmpty()) {
            return null;
        }
        return new BuscarEquiposTask(org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class));
    }

    private class BuscarEquiposTask extends org.jdesktop.application.Task<Object, Void> {

        ArrayList<Equipos> eqList = new ArrayList<Equipos>();
        String query = queryEq.getText();

        BuscarEquiposTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to BuscarEquiposTask fields, here.
            super(app);
        }

        @Override
        protected Object doInBackground() {
            // Your Task's code here.  This method runs
            // on a background thread, so don't reference
            // the Swing GUI from here.
            EquiposDAO edao = new EquiposDAO();
            edao.conectar();
            eqList = edao.buscarDIMA(query);
            return null;  // return your result
        }

        @Override
        protected void succeeded(Object result) {
            listEq.removeAllElements();
            if (eqList.isEmpty()) {
                listEq.addElement("Sin resultados");
                listaEquipo.setEnabled(false);
            } else {
                for (int i = 0; i < eqList.size(); i++) {
                    listEq.addElement((Equipos) eqList.get(i));
                }
                listaEquipo.setEnabled(true);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TareaAsignadaText;
    private javax.swing.JButton aceptarInfoTransporte;
    private javax.swing.JButton botonBuscarEmpleadoMostrar;
    private javax.swing.JButton botonBuscarEquipoMostrar;
    private javax.swing.JButton botonQuery;
    private javax.swing.JButton botonQueryEq;
    private javax.swing.JDialog buscarEmpleado;
    private javax.swing.JDialog buscarEquipo;
    private javax.swing.JTextField cantidadLitrosText;
    private javax.swing.JButton cargarDatosTransporte;
    private javax.swing.JButton cerrarInfoTransporte;
    private javax.swing.JButton cerrarParteBoton;
    private javax.swing.JComboBox comboEquipos;
    private javax.swing.JComboBox comboFuncion;
    private javax.swing.JComboBox comboObra;
    private javax.swing.JComboBox comboOperario;
    private javax.swing.JDialog datosTransporteDialog;
    private javax.swing.JPanel equipoPanel;
    private javax.swing.JComboBox estacionesCombo;
    private javax.swing.JButton exitDialog;
    private javax.swing.JButton exitDialogEq;
    private com.toedter.calendar.JDateChooser fechaParte;
    private javax.swing.JTextField finalHorometroText;
    private javax.swing.JTextField finalOdometroText;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JButton guardarParteBoton;
    private javax.swing.JPanel horarioPanel;
    private javax.swing.JTextField inicialHorometroText;
    private javax.swing.JTextField inicialOdometroText;
    private javax.swing.JCheckBox isCrearOT;
    private javax.swing.JCheckBox isDesarrango;
    private javax.swing.JCheckBox isTransporte;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList listaEmpleados;
    private javax.swing.JList listaEquipo;
    private javax.swing.JCheckBox multifuncionCheck;
    private javax.swing.JTextField numPre;
    private javax.swing.JTextField numPro;
    private javax.swing.JTextArea observacionesText;
    private javax.swing.JLabel outText;
    private javax.swing.JPanel panelAzul2;
    private javax.swing.JTextField query1;
    private javax.swing.JTextField queryEq;
    private javax.swing.JButton selectEquipo;
    private javax.swing.JButton selectRow;
    private javax.swing.JTable tablaHorario;
    private javax.swing.JTable tablaTransporte;
    // End of variables declaration//GEN-END:variables
    public static DefaultComboBoxModel funciones = new DefaultComboBoxModel();
    public static DefaultComboBoxModel obras = new DefaultComboBoxModel();
    public static DefaultComboBoxModel operarios = new DefaultComboBoxModel();
    public static DefaultComboBoxModel equipos = new DefaultComboBoxModel();
    public static DefaultComboBoxModel estaciones = new DefaultComboBoxModel();
    public static TablaHorarioIngresoModel tablaModel = new TablaHorarioIngresoModel();
    public static TablaDatosTransporte tdt = new TablaDatosTransporte();
    DefaultListModel listEmpl = new DefaultListModel();
    DefaultListModel listEq = new DefaultListModel();
    public String newFc = "";
    public List<String[]> materialesList = new ArrayList<String[]>();
    public ArrayList<Materiales> regDatosTransp = new ArrayList<Materiales>();
    public Perfiles perfil = new Perfiles();
    boolean esp = true;
    
    //datos del parte seleccionado
    static public ParteDiario pd = new ParteDiario();
    static public Registro reg = new Registro();
    static public Materiales mat = new Materiales();
    static public RegistroEquipo regEq = new RegistroEquipo();
    static public ArrayList<Materiales> datosTr = new ArrayList<Materiales>();
    static public Obras obra = new Obras();
}
