/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDFamiliaEquipo.java
 *
 * Created on 29/12/2014, 12:46:49
 */
package zilleprojects.form;

import DAO.FamiliaEquipoDAO;
import DAO.IAbstractDAO;
import Modelo.EntidadAbstracta;
import Modelo.FamiliaEquipo;
import Modelo.tablemodel.FamiliaEquipoTableModel;
import Modelo.tablemodel.ZilleAbstractTableModel;
import java.awt.Dimension;
import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JDialog;
import org.jdesktop.application.Action;
import zilleprojects.ZilleProjectsApp;

/**
 *
 * @author m4tuu
 */
public class JDFamiliaEquipo extends ZilleDialog {
    Frame parent;
    /** Creates new form JDFamiliaEquipo */
    public JDFamiliaEquipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        SetButtonExtra(btnVerHistoricos);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVerHistoricos = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class).getContext().getResourceMap(JDFamiliaEquipo.class);
        jDialog1.setTitle(resourceMap.getString("jDialog1.title")); // NOI18N
        jDialog1.setAlwaysOnTop(true);
        jDialog1.setModal(true);
        jDialog1.setName("jDialog1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        txtNombre.setText(resourceMap.getString("txtNombre.text")); // NOI18N
        txtNombre.setName("txtNombre"); // NOI18N
        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(zilleprojects.ZilleProjectsApp.class).getContext().getActionMap(JDFamiliaEquipo.class, this);
        btnAceptar.setAction(actionMap.get("GuardarEntidad"));
        btnAceptar.setIcon(resourceMap.getIcon("btnAceptar.icon")); // NOI18N
        btnAceptar.setText(resourceMap.getString("btnAceptar.text")); // NOI18N
        btnAceptar.setName("btnAceptar"); // NOI18N

        btnCancelar.setIcon(resourceMap.getIcon("btnCancelar.icon")); // NOI18N
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAceptar, btnCancelar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAceptar, btnCancelar});

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        
        btnVerHistoricos.setAction(actionMap.get("mostrarHistoricos")); // NOI18N
        btnVerHistoricos.setText(resourceMap.getString("btnVerHistoricos.text")); // NOI18N
        btnVerHistoricos.setName("btnVerHistoricos"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        getAMEntidad().dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDFamiliaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDFamiliaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDFamiliaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDFamiliaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDFamiliaEquipo dialog = new JDFamiliaEquipo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVerHistoricos;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    protected String getTablaName() {
        return "familia_equipo";
    }

    @Override
    protected String getNombreEntidad() {
        return "Familia de equipos";
    }

    @Override
    protected void limpiarEntidad() {
        familiaSelected = new FamiliaEquipo();
        txtNombre.setText(null);
    }

    @Override
    protected IAbstractDAO getDao() {
        return new FamiliaEquipoDAO();
    }

    
    @Override
    protected EntidadAbstracta getEntidadAbstracta() {
        return familiaSelected;
    }

    @Override
    protected void setEntidadAbstracta(EntidadAbstracta ea) {
        familiaSelected = (FamiliaEquipo) ea;
    }

    @Override
    protected ZilleAbstractTableModel getTableModel() {
        return tableModel;
    }

    @Override
    protected ZilleAbstractTableModel setNewTableModel() {
        tableModel = new FamiliaEquipoTableModel();
        return tableModel;
    }

    @Override
    protected void setTableModel(ZilleAbstractTableModel ea) {
        tableModel = (FamiliaEquipoTableModel) ea;
    }

    @Override
    protected void setTitulo() {
        setTitle("Administrador de familias de equipo");
    }

    @Override
    protected JDialog getAMEntidad() {
        return jDialog1;
    }

    @Override
    protected JButton getBtnAceptarEntidadEdit() {
        return btnAceptar;
    }

    @Override
    protected JButton getBtnCancelarEntidadEdit() {
        return btnCancelar;
    }

    @Override
    protected void CargarEntidadAlEditar(EntidadAbstracta entidad) {
        familiaSelected = (FamiliaEquipo) entidad;
        txtNombre.setText(familiaSelected.getNombre());      
    }

    @Override
    protected boolean GuardarEntidadAlEditar() {
        familiaSelected.setNombre(txtNombre.getText());
        return familiaSelected.validate();
    }

    @Override
    protected Dimension getSizeDialogEdit() {
        return new Dimension(400, 150);
    }

    @Action
    public void mostrarHistoricos() {
        if(getTabla().getSelectedRow( )> -1 && familiaSelected.getId() != 0) {
            JDPrecioHistorico dialog = new JDPrecioHistorico(this.parent, true, familiaSelected);
            ZilleProjectsApp.getApplication().show(dialog);
        } else {
            Error("Información", "Debe seleccionar una familia");
        }
    }
    
    private FamiliaEquipoTableModel tableModel = new FamiliaEquipoTableModel();
    private FamiliaEquipo familiaSelected = new FamiliaEquipo();
}
